// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sealevel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ELFLoaderEffects struct {
	_tab flatbuffers.Table
}

func GetRootAsELFLoaderEffects(buf []byte, offset flatbuffers.UOffsetT) *ELFLoaderEffects {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ELFLoaderEffects{}
	x.Init(buf, n+offset)
	return x
}

func FinishELFLoaderEffectsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsELFLoaderEffects(buf []byte, offset flatbuffers.UOffsetT) *ELFLoaderEffects {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ELFLoaderEffects{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedELFLoaderEffectsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ELFLoaderEffects) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ELFLoaderEffects) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ELFLoaderEffects) ErrCode() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ELFLoaderEffects) MutateErrCode(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *ELFLoaderEffects) RodataHash(obj *XXHash) *XXHash {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(XXHash)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ELFLoaderEffects) TextCnt() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ELFLoaderEffects) MutateTextCnt(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *ELFLoaderEffects) TextOff() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ELFLoaderEffects) MutateTextOff(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *ELFLoaderEffects) EntryPc() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ELFLoaderEffects) MutateEntryPc(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *ELFLoaderEffects) CalldestsHash(obj *XXHash) *XXHash {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(XXHash)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ELFLoaderEffectsStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ELFLoaderEffectsAddErrCode(builder *flatbuffers.Builder, errCode byte) {
	builder.PrependByteSlot(0, errCode, 0)
}
func ELFLoaderEffectsAddRodataHash(builder *flatbuffers.Builder, rodataHash flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(rodataHash), 0)
}
func ELFLoaderEffectsAddTextCnt(builder *flatbuffers.Builder, textCnt uint64) {
	builder.PrependUint64Slot(2, textCnt, 0)
}
func ELFLoaderEffectsAddTextOff(builder *flatbuffers.Builder, textOff uint64) {
	builder.PrependUint64Slot(3, textOff, 0)
}
func ELFLoaderEffectsAddEntryPc(builder *flatbuffers.Builder, entryPc uint64) {
	builder.PrependUint64Slot(4, entryPc, 0)
}
func ELFLoaderEffectsAddCalldestsHash(builder *flatbuffers.Builder, calldestsHash flatbuffers.UOffsetT) {
	builder.PrependStructSlot(5, flatbuffers.UOffsetT(calldestsHash), 0)
}
func ELFLoaderEffectsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
