// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sealevel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ELFLoaderFixture struct {
	_tab flatbuffers.Table
}

func GetRootAsELFLoaderFixture(buf []byte, offset flatbuffers.UOffsetT) *ELFLoaderFixture {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ELFLoaderFixture{}
	x.Init(buf, n+offset)
	return x
}

func FinishELFLoaderFixtureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsELFLoaderFixture(buf []byte, offset flatbuffers.UOffsetT) *ELFLoaderFixture {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ELFLoaderFixture{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedELFLoaderFixtureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ELFLoaderFixture) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ELFLoaderFixture) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ELFLoaderFixture) Metadata(obj *FixtureMetadata) *FixtureMetadata {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FixtureMetadata)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ELFLoaderFixture) Input(obj *ELFLoaderCtx) *ELFLoaderCtx {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ELFLoaderCtx)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ELFLoaderFixture) Output(obj *ELFLoaderEffects) *ELFLoaderEffects {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ELFLoaderEffects)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ELFLoaderFixtureStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ELFLoaderFixtureAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(metadata), 0)
}
func ELFLoaderFixtureAddInput(builder *flatbuffers.Builder, input flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(input), 0)
}
func ELFLoaderFixtureAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(output), 0)
}
func ELFLoaderFixtureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
