// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sealevel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ELFLoaderCtx struct {
	_tab flatbuffers.Table
}

func GetRootAsELFLoaderCtx(buf []byte, offset flatbuffers.UOffsetT) *ELFLoaderCtx {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ELFLoaderCtx{}
	x.Init(buf, n+offset)
	return x
}

func FinishELFLoaderCtxBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsELFLoaderCtx(buf []byte, offset flatbuffers.UOffsetT) *ELFLoaderCtx {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ELFLoaderCtx{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedELFLoaderCtxBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ELFLoaderCtx) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ELFLoaderCtx) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ELFLoaderCtx) ElfData(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ELFLoaderCtx) ElfDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ELFLoaderCtx) ElfDataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ELFLoaderCtx) MutateElfData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ELFLoaderCtx) Features(obj *FeatureSet) *FeatureSet {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FeatureSet)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ELFLoaderCtx) DeployChecks() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ELFLoaderCtx) MutateDeployChecks(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func ELFLoaderCtxStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ELFLoaderCtxAddElfData(builder *flatbuffers.Builder, elfData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(elfData), 0)
}
func ELFLoaderCtxStartElfDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ELFLoaderCtxAddFeatures(builder *flatbuffers.Builder, features flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(features), 0)
}
func ELFLoaderCtxAddDeployChecks(builder *flatbuffers.Builder, deployChecks bool) {
	builder.PrependBoolSlot(2, deployChecks, false)
}
func ELFLoaderCtxEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
