// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sealevel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FeatureSet struct {
	_tab flatbuffers.Table
}

func GetRootAsFeatureSet(buf []byte, offset flatbuffers.UOffsetT) *FeatureSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FeatureSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishFeatureSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFeatureSet(buf []byte, offset flatbuffers.UOffsetT) *FeatureSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FeatureSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFeatureSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FeatureSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FeatureSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FeatureSet) Features(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *FeatureSet) FeaturesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FeatureSet) MutateFeatures(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func FeatureSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FeatureSetAddFeatures(builder *flatbuffers.Builder, features flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(features), 0)
}
func FeatureSetStartFeaturesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func FeatureSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
