// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sealevel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FixtureMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsFixtureMetadata(buf []byte, offset flatbuffers.UOffsetT) *FixtureMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FixtureMetadata{}
	x.Init(buf, n+offset)
	return x
}

func FinishFixtureMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFixtureMetadata(buf []byte, offset flatbuffers.UOffsetT) *FixtureMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FixtureMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFixtureMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FixtureMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FixtureMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FixtureMetadata) FnEntrypoint() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FixtureMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FixtureMetadataAddFnEntrypoint(builder *flatbuffers.Builder, fnEntrypoint flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fnEntrypoint), 0)
}
func FixtureMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
