// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sealevel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type XXHash struct {
	_tab flatbuffers.Struct
}

func (rcv *XXHash) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *XXHash) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *XXHash) H0() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *XXHash) MutateH0(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *XXHash) H1() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(1))
}
func (rcv *XXHash) MutateH1(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(1), n)
}

func (rcv *XXHash) H2() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *XXHash) MutateH2(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *XXHash) H3() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(3))
}
func (rcv *XXHash) MutateH3(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(3), n)
}

func (rcv *XXHash) H4() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *XXHash) MutateH4(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *XXHash) H5() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(5))
}
func (rcv *XXHash) MutateH5(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(5), n)
}

func (rcv *XXHash) H6() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *XXHash) MutateH6(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *XXHash) H7() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(7))
}
func (rcv *XXHash) MutateH7(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(7), n)
}

func CreateXXHash(builder *flatbuffers.Builder, h0 byte, h1 byte, h2 byte, h3 byte, h4 byte, h5 byte, h6 byte, h7 byte) flatbuffers.UOffsetT {
	builder.Prep(1, 8)
	builder.PrependByte(h7)
	builder.PrependByte(h6)
	builder.PrependByte(h5)
	builder.PrependByte(h4)
	builder.PrependByte(h3)
	builder.PrependByte(h2)
	builder.PrependByte(h1)
	builder.PrependByte(h0)
	return builder.Offset()
}
