package alpenglow

import (
	"crypto/ed25519"
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/require"
)

// Vector generated by Agave master fbdcd41e08def72c4e1cb7ffc489b4e0c13fba49
// using solana-bls-signatures 3.3.0 and keypair_from_seed([7; 32]).
func TestBLSSignerMatchesAgave(t *testing.T) {
	identity := ed25519.NewKeyFromSeed(bytesOf(7, ed25519.SeedSize))
	signer, err := DeriveBLSSigner(identity)
	require.NoError(t, err)
	public := signer.PublicKeyCompressed()
	require.Equal(t,
		"a55384b86c60c0e2a13ffdf9087c94495455083acf06ff23d8e7416ee1df1cafccfaad802b527ade7dfe1b02a6bfd79a",
		hex.EncodeToString(public[:]),
	)
	payload, err := EncodeVotePayloadToSign(NewSkipVote(42), 1337)
	require.NoError(t, err)
	require.Equal(t, "032a000000000000003905", hex.EncodeToString(payload))
	signature, err := signer.Sign(payload)
	require.NoError(t, err)
	require.Equal(t,
		"004884dc35c2f59863c57a271d3d615244e112823f77f533f0e16db2c2e00c3c85fc6a5c049008a14c6a8c4873bcb70c06f5b4216421f883f8c76db787cbf7ad32c7d4fc9be5480495fcff6441a202c2f93ba38c3a432d32d190eee9daed9d401345ad227b8bdfb38f7a8a2e17a29b45d069029f264433e2692d1c480d76fb5fa2b41fb8b2bf97bcfb6b5c0991961e5e03d71e4f219fa8bef14862c7c8a2c4269c361e448c9c52f2aaccab1ecc181aa4de41f5d8944d298fb193cc209a977a5c",
		hex.EncodeToString(signature),
	)
}

func bytesOf(value byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = value
	}
	return out
}
