# Mithril Starter Configuration
# Ready to use with default setup script paths.
# For advanced options, see mithril.example.toml

name = "mithril"

[ledger]
    accounts_path = "/mnt/mithril-accounts"
    path = "/mnt/mithril-ledger/blockstore"
    snapshot_archive_path = "/mnt/mithril-ledger/snapshots"

[rpc]
    rpc = ["https://api.mainnet-beta.solana.com"]
    # port = 8899  # Uncomment to enable Mithril's RPC server

[snapshot]
    download_path = "/mnt/mithril-ledger/snapshots"
    # save_to_disk = true  # Uncomment to save snapshots while streaming
    # verbose = true       # Uncomment for detailed snapshot finder output
