package configcmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var (
	// ConfigCmd is the parent command for config-related subcommands
	ConfigCmd = cobra.Command{
		Use:   "config",
		Short: "Configuration management commands",
	}

	// InitCmd creates a starter config.toml
	InitCmd = cobra.Command{
		Use:   "init",
		Short: "Create a starter config.toml from the example template",
		Long: `Creates a config.toml file in the current directory with sensible defaults.

The generated config has all parameters with good defaults - you only need to
customize the storage paths for your setup.

If config.toml already exists, this command will not overwrite it.`,
		Run: func(cmd *cobra.Command, args []string) {
			runConfigInit()
		},
	}

	outputPath string
)

func init() {
	ConfigCmd.AddCommand(&InitCmd)
	InitCmd.Flags().StringVarP(&outputPath, "output", "o", "config.toml", "Output path for config file")
}

func runConfigInit() {
	// Check if file already exists
	if _, err := os.Stat(outputPath); err == nil {
		fmt.Printf("Error: %s already exists. Remove it first or use -o to specify a different path.\n", outputPath)
		os.Exit(1)
	}

	// Generate the config content
	config := generateStarterConfig()

	// Write to file
	if err := os.WriteFile(outputPath, []byte(config), 0644); err != nil {
		fmt.Printf("Error writing config file: %v\n", err)
		os.Exit(1)
	}

	absPath, _ := filepath.Abs(outputPath)
	fmt.Printf("Created %s\n", absPath)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Edit the [storage] paths for your setup")
	fmt.Println("  2. Run: mithril run --config config.toml")
	fmt.Println()
	fmt.Println("See config.example.toml for detailed documentation of all options.")
}

func generateStarterConfig() string {
	return `# Mithril Configuration
# Generated by: mithril config init
# See config.example.toml for detailed documentation of all options.

name = "mithril"

[bootstrap]
mode = "snapshot"   # "auto" | "snapshot" | "accountsdb"

[storage]
accounts = "/mnt/mithril-accounts"           # AccountsDB (~500GB, use fastest NVMe)
blockstore = "/mnt/mithril-ledger/blockstore"
snapshots = "/mnt/mithril-ledger/snapshots"  # ~100GB for full + incremental

[network]
rpc = ["https://api.mainnet-beta.solana.com"]

[block]
source = "rpc"   # "rpc" | "overcast"
# overcast_endpoint = "localhost:9000"

[replay]
txpar = 24   # Recommended: 2x your CPU core count

[rpc]
port = 8899  # Mithril's RPC server (localhost only)

# Advanced options (defaults work well for most setups)
# See config.example.toml for: [tuning], [debug], [snapshot], [reporting]
`
}
