// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slot_stream.proto

package overcast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SlotStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotStreamRequest) Reset()         { *m = SlotStreamRequest{} }
func (m *SlotStreamRequest) String() string { return proto.CompactTextString(m) }
func (*SlotStreamRequest) ProtoMessage()    {}
func (*SlotStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c19f589a091a56a, []int{0}
}

func (m *SlotStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotStreamRequest.Unmarshal(m, b)
}
func (m *SlotStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotStreamRequest.Marshal(b, m, deterministic)
}
func (m *SlotStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotStreamRequest.Merge(m, src)
}
func (m *SlotStreamRequest) XXX_Size() int {
	return xxx_messageInfo_SlotStreamRequest.Size(m)
}
func (m *SlotStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SlotStreamRequest proto.InternalMessageInfo

type SlotResponse struct {
	Entries              []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Slot                 uint64   `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotResponse) Reset()         { *m = SlotResponse{} }
func (m *SlotResponse) String() string { return proto.CompactTextString(m) }
func (*SlotResponse) ProtoMessage()    {}
func (*SlotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c19f589a091a56a, []int{1}
}

func (m *SlotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotResponse.Unmarshal(m, b)
}
func (m *SlotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotResponse.Marshal(b, m, deterministic)
}
func (m *SlotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotResponse.Merge(m, src)
}
func (m *SlotResponse) XXX_Size() int {
	return xxx_messageInfo_SlotResponse.Size(m)
}
func (m *SlotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlotResponse proto.InternalMessageInfo

func (m *SlotResponse) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *SlotResponse) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func init() {
	proto.RegisterType((*SlotStreamRequest)(nil), "slot_stream.SlotStreamRequest")
	proto.RegisterType((*SlotResponse)(nil), "slot_stream.SlotResponse")
}

func init() {
	proto.RegisterFile("slot_stream.proto", fileDescriptor_8c19f589a091a56a)
}

var fileDescriptor_8c19f589a091a56a = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xce, 0xc9, 0x2f,
	0x89, 0x2f, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x92, 0x12, 0x00, 0x73, 0x52, 0xf3, 0x4a, 0x8a, 0x2a, 0x21, 0xd2, 0x4a, 0xc2, 0x5c, 0x82,
	0xc1, 0x39, 0xf9, 0x25, 0xc1, 0x60, 0xf9, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x7f,
	0x2e, 0x1e, 0x90, 0x60, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x36, 0x17, 0x3b,
	0x48, 0x4f, 0x66, 0x6a, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xa0, 0x1e, 0x92, 0x41,
	0xae, 0x20, 0x32, 0x08, 0xa6, 0x42, 0x48, 0x88, 0x8b, 0x05, 0x24, 0x29, 0xc1, 0xa4, 0xc0, 0xa8,
	0xc1, 0x12, 0x04, 0x66, 0x1b, 0x45, 0x70, 0x71, 0x21, 0x6c, 0x11, 0xf2, 0xe2, 0xe2, 0x86, 0xb0,
	0x40, 0x62, 0xc5, 0x42, 0x72, 0x7a, 0xc8, 0xae, 0xc6, 0x70, 0x8d, 0x94, 0x24, 0x86, 0x3c, 0xcc,
	0x61, 0x06, 0x8c, 0x4e, 0xdc, 0x51, 0x9c, 0xfa, 0xf9, 0x65, 0xa9, 0x45, 0xc9, 0x89, 0xc5, 0x25,
	0x49, 0x6c, 0x60, 0x3f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x72, 0x94, 0x8d, 0xec, 0x07,
	0x01, 0x00, 0x00,
}
