// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: slot_stream.proto

package overcast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotStreamRequest) Reset() {
	*x = SlotStreamRequest{}
	mi := &file_slot_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotStreamRequest) ProtoMessage() {}

func (x *SlotStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slot_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotStreamRequest.ProtoReflect.Descriptor instead.
func (*SlotStreamRequest) Descriptor() ([]byte, []int) {
	return file_slot_stream_proto_rawDescGZIP(), []int{0}
}

type SlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // JSON encoded entries
	Slot          uint64                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	ParentSlot    uint64                 `protobuf:"varint,3,opt,name=parent_slot,json=parentSlot,proto3" json:"parent_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotResponse) Reset() {
	*x = SlotResponse{}
	mi := &file_slot_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotResponse) ProtoMessage() {}

func (x *SlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slot_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotResponse.ProtoReflect.Descriptor instead.
func (*SlotResponse) Descriptor() ([]byte, []int) {
	return file_slot_stream_proto_rawDescGZIP(), []int{1}
}

func (x *SlotResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SlotResponse) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotResponse) GetParentSlot() uint64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

var File_slot_stream_proto protoreflect.FileDescriptor

const file_slot_stream_proto_rawDesc = "" +
	"\n" +
	"\x11slot_stream.proto\x12\vslot_stream\x1a\x10slot_entry.proto\"\x13\n" +
	"\x11SlotStreamRequest\"p\n" +
	"\fSlotResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.slot_entry.EntryR\aentries\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12\x1f\n" +
	"\vparent_slot\x18\x03 \x01(\x04R\n" +
	"parentSlot2X\n" +
	"\n" +
	"SlotStream\x12J\n" +
	"\vStreamSlots\x12\x1e.slot_stream.SlotStreamRequest\x1a\x19.slot_stream.SlotResponse0\x01B\vZ\t/overcastb\x06proto3"

var (
	file_slot_stream_proto_rawDescOnce sync.Once
	file_slot_stream_proto_rawDescData []byte
)

func file_slot_stream_proto_rawDescGZIP() []byte {
	file_slot_stream_proto_rawDescOnce.Do(func() {
		file_slot_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slot_stream_proto_rawDesc), len(file_slot_stream_proto_rawDesc)))
	})
	return file_slot_stream_proto_rawDescData
}

var file_slot_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_slot_stream_proto_goTypes = []any{
	(*SlotStreamRequest)(nil), // 0: slot_stream.SlotStreamRequest
	(*SlotResponse)(nil),      // 1: slot_stream.SlotResponse
	(*Entry)(nil),             // 2: slot_entry.Entry
}
var file_slot_stream_proto_depIdxs = []int32{
	2, // 0: slot_stream.SlotResponse.entries:type_name -> slot_entry.Entry
	0, // 1: slot_stream.SlotStream.StreamSlots:input_type -> slot_stream.SlotStreamRequest
	1, // 2: slot_stream.SlotStream.StreamSlots:output_type -> slot_stream.SlotResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_slot_stream_proto_init() }
func file_slot_stream_proto_init() {
	if File_slot_stream_proto != nil {
		return
	}
	file_slot_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slot_stream_proto_rawDesc), len(file_slot_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slot_stream_proto_goTypes,
		DependencyIndexes: file_slot_stream_proto_depIdxs,
		MessageInfos:      file_slot_stream_proto_msgTypes,
	}.Build()
	File_slot_stream_proto = out.File
	file_slot_stream_proto_goTypes = nil
	file_slot_stream_proto_depIdxs = nil
}
