// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: slot_entry.proto

package overcast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageHeader struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	NumRequiredSignatures       uint32                 `protobuf:"varint,1,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32                 `protobuf:"varint,2,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32                 `protobuf:"varint,3,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_slot_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_slot_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_slot_entry_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetNumRequiredSignatures() uint32 {
	if x != nil {
		return x.NumRequiredSignatures
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlySignedAccounts
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlyUnsignedAccounts
	}
	return 0
}

type CompiledInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Accounts       []byte                 `protobuf:"bytes,2,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompiledInstruction) Reset() {
	*x = CompiledInstruction{}
	mi := &file_slot_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledInstruction) ProtoMessage() {}

func (x *CompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_slot_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledInstruction.ProtoReflect.Descriptor instead.
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return file_slot_entry_proto_rawDescGZIP(), []int{1}
}

func (x *CompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *CompiledInstruction) GetAccounts() []byte {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *CompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageAddressTableLookup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32 bytes pubkey
	AccountKey      []byte `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WritableIndexes []byte `protobuf:"bytes,2,opt,name=writable_indexes,json=writableIndexes,proto3" json:"writable_indexes,omitempty"`
	ReadonlyIndexes []byte `protobuf:"bytes,3,opt,name=readonly_indexes,json=readonlyIndexes,proto3" json:"readonly_indexes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageAddressTableLookup) Reset() {
	*x = MessageAddressTableLookup{}
	mi := &file_slot_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAddressTableLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAddressTableLookup) ProtoMessage() {}

func (x *MessageAddressTableLookup) ProtoReflect() protoreflect.Message {
	mi := &file_slot_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAddressTableLookup.ProtoReflect.Descriptor instead.
func (*MessageAddressTableLookup) Descriptor() ([]byte, []int) {
	return file_slot_entry_proto_rawDescGZIP(), []int{2}
}

func (x *MessageAddressTableLookup) GetAccountKey() []byte {
	if x != nil {
		return x.AccountKey
	}
	return nil
}

func (x *MessageAddressTableLookup) GetWritableIndexes() []byte {
	if x != nil {
		return x.WritableIndexes
	}
	return nil
}

func (x *MessageAddressTableLookup) GetReadonlyIndexes() []byte {
	if x != nil {
		return x.ReadonlyIndexes
	}
	return nil
}

type VersionedMessageLegacy struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Each key is a 32 bytes pubkey
	AccountKeys [][]byte `protobuf:"bytes,2,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	// 32 byte hash
	RecentBlockhash []byte                 `protobuf:"bytes,3,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Instructions    []*CompiledInstruction `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VersionedMessageLegacy) Reset() {
	*x = VersionedMessageLegacy{}
	mi := &file_slot_entry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedMessageLegacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedMessageLegacy) ProtoMessage() {}

func (x *VersionedMessageLegacy) ProtoReflect() protoreflect.Message {
	mi := &file_slot_entry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedMessageLegacy.ProtoReflect.Descriptor instead.
func (*VersionedMessageLegacy) Descriptor() ([]byte, []int) {
	return file_slot_entry_proto_rawDescGZIP(), []int{3}
}

func (x *VersionedMessageLegacy) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VersionedMessageLegacy) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *VersionedMessageLegacy) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *VersionedMessageLegacy) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type VersionedMessageV0 struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Each key is a 32 bytes pubkey
	AccountKeys [][]byte `protobuf:"bytes,2,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	// 32 byte hash
	RecentBlockhash     []byte                       `protobuf:"bytes,3,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Instructions        []*CompiledInstruction       `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty"`
	AddressTableLookups []*MessageAddressTableLookup `protobuf:"bytes,5,rep,name=address_table_lookups,json=addressTableLookups,proto3" json:"address_table_lookups,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VersionedMessageV0) Reset() {
	*x = VersionedMessageV0{}
	mi := &file_slot_entry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedMessageV0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedMessageV0) ProtoMessage() {}

func (x *VersionedMessageV0) ProtoReflect() protoreflect.Message {
	mi := &file_slot_entry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedMessageV0.ProtoReflect.Descriptor instead.
func (*VersionedMessageV0) Descriptor() ([]byte, []int) {
	return file_slot_entry_proto_rawDescGZIP(), []int{4}
}

func (x *VersionedMessageV0) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VersionedMessageV0) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *VersionedMessageV0) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *VersionedMessageV0) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *VersionedMessageV0) GetAddressTableLookups() []*MessageAddressTableLookup {
	if x != nil {
		return x.AddressTableLookups
	}
	return nil
}

type VersionedTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each signature is 64 bytes
	Signatures [][]byte `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*VersionedTransaction_MessageLegacy
	//	*VersionedTransaction_MessageV0
	Message       isVersionedTransaction_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedTransaction) Reset() {
	*x = VersionedTransaction{}
	mi := &file_slot_entry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedTransaction) ProtoMessage() {}

func (x *VersionedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_slot_entry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedTransaction.ProtoReflect.Descriptor instead.
func (*VersionedTransaction) Descriptor() ([]byte, []int) {
	return file_slot_entry_proto_rawDescGZIP(), []int{5}
}

func (x *VersionedTransaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *VersionedTransaction) GetMessage() isVersionedTransaction_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *VersionedTransaction) GetMessageLegacy() *VersionedMessageLegacy {
	if x != nil {
		if x, ok := x.Message.(*VersionedTransaction_MessageLegacy); ok {
			return x.MessageLegacy
		}
	}
	return nil
}

func (x *VersionedTransaction) GetMessageV0() *VersionedMessageV0 {
	if x != nil {
		if x, ok := x.Message.(*VersionedTransaction_MessageV0); ok {
			return x.MessageV0
		}
	}
	return nil
}

type isVersionedTransaction_Message interface {
	isVersionedTransaction_Message()
}

type VersionedTransaction_MessageLegacy struct {
	MessageLegacy *VersionedMessageLegacy `protobuf:"bytes,2,opt,name=message_legacy,json=messageLegacy,proto3,oneof"`
}

type VersionedTransaction_MessageV0 struct {
	MessageV0 *VersionedMessageV0 `protobuf:"bytes,3,opt,name=message_v0,json=messageV0,proto3,oneof"`
}

func (*VersionedTransaction_MessageLegacy) isVersionedTransaction_Message() {}

func (*VersionedTransaction_MessageV0) isVersionedTransaction_Message() {}

type Entry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NumHashes uint64                 `protobuf:"varint,1,opt,name=num_hashes,json=numHashes,proto3" json:"num_hashes,omitempty"`
	// fixed size, 32 bytes
	Hash          []byte                  `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Transactions  []*VersionedTransaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_slot_entry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_slot_entry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_slot_entry_proto_rawDescGZIP(), []int{6}
}

func (x *Entry) GetNumHashes() uint64 {
	if x != nil {
		return x.NumHashes
	}
	return 0
}

func (x *Entry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Entry) GetTransactions() []*VersionedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_slot_entry_proto protoreflect.FileDescriptor

const file_slot_entry_proto_rawDesc = "" +
	"\n" +
	"\x10slot_entry.proto\x12\n" +
	"slot_entry\"\xcd\x01\n" +
	"\rMessageHeader\x126\n" +
	"\x17num_required_signatures\x18\x01 \x01(\rR\x15numRequiredSignatures\x12?\n" +
	"\x1cnum_readonly_signed_accounts\x18\x02 \x01(\rR\x19numReadonlySignedAccounts\x12C\n" +
	"\x1enum_readonly_unsigned_accounts\x18\x03 \x01(\rR\x1bnumReadonlyUnsignedAccounts\"o\n" +
	"\x13CompiledInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x01(\fR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x92\x01\n" +
	"\x19MessageAddressTableLookup\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\fR\n" +
	"accountKey\x12)\n" +
	"\x10writable_indexes\x18\x02 \x01(\fR\x0fwritableIndexes\x12)\n" +
	"\x10readonly_indexes\x18\x03 \x01(\fR\x0freadonlyIndexes\"\xde\x01\n" +
	"\x16VersionedMessageLegacy\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.slot_entry.MessageHeaderR\x06header\x12!\n" +
	"\faccount_keys\x18\x02 \x03(\fR\vaccountKeys\x12)\n" +
	"\x10recent_blockhash\x18\x03 \x01(\fR\x0frecentBlockhash\x12C\n" +
	"\finstructions\x18\x04 \x03(\v2\x1f.slot_entry.CompiledInstructionR\finstructions\"\xb5\x02\n" +
	"\x12VersionedMessageV0\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.slot_entry.MessageHeaderR\x06header\x12!\n" +
	"\faccount_keys\x18\x02 \x03(\fR\vaccountKeys\x12)\n" +
	"\x10recent_blockhash\x18\x03 \x01(\fR\x0frecentBlockhash\x12C\n" +
	"\finstructions\x18\x04 \x03(\v2\x1f.slot_entry.CompiledInstructionR\finstructions\x12Y\n" +
	"\x15address_table_lookups\x18\x05 \x03(\v2%.slot_entry.MessageAddressTableLookupR\x13addressTableLookups\"\xcf\x01\n" +
	"\x14VersionedTransaction\x12\x1e\n" +
	"\n" +
	"signatures\x18\x01 \x03(\fR\n" +
	"signatures\x12K\n" +
	"\x0emessage_legacy\x18\x02 \x01(\v2\".slot_entry.VersionedMessageLegacyH\x00R\rmessageLegacy\x12?\n" +
	"\n" +
	"message_v0\x18\x03 \x01(\v2\x1e.slot_entry.VersionedMessageV0H\x00R\tmessageV0B\t\n" +
	"\amessage\"\x80\x01\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"num_hashes\x18\x01 \x01(\x04R\tnumHashes\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12D\n" +
	"\ftransactions\x18\x03 \x03(\v2 .slot_entry.VersionedTransactionR\ftransactionsB\vZ\t/overcastb\x06proto3"

var (
	file_slot_entry_proto_rawDescOnce sync.Once
	file_slot_entry_proto_rawDescData []byte
)

func file_slot_entry_proto_rawDescGZIP() []byte {
	file_slot_entry_proto_rawDescOnce.Do(func() {
		file_slot_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slot_entry_proto_rawDesc), len(file_slot_entry_proto_rawDesc)))
	})
	return file_slot_entry_proto_rawDescData
}

var file_slot_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_slot_entry_proto_goTypes = []any{
	(*MessageHeader)(nil),             // 0: slot_entry.MessageHeader
	(*CompiledInstruction)(nil),       // 1: slot_entry.CompiledInstruction
	(*MessageAddressTableLookup)(nil), // 2: slot_entry.MessageAddressTableLookup
	(*VersionedMessageLegacy)(nil),    // 3: slot_entry.VersionedMessageLegacy
	(*VersionedMessageV0)(nil),        // 4: slot_entry.VersionedMessageV0
	(*VersionedTransaction)(nil),      // 5: slot_entry.VersionedTransaction
	(*Entry)(nil),                     // 6: slot_entry.Entry
}
var file_slot_entry_proto_depIdxs = []int32{
	0, // 0: slot_entry.VersionedMessageLegacy.header:type_name -> slot_entry.MessageHeader
	1, // 1: slot_entry.VersionedMessageLegacy.instructions:type_name -> slot_entry.CompiledInstruction
	0, // 2: slot_entry.VersionedMessageV0.header:type_name -> slot_entry.MessageHeader
	1, // 3: slot_entry.VersionedMessageV0.instructions:type_name -> slot_entry.CompiledInstruction
	2, // 4: slot_entry.VersionedMessageV0.address_table_lookups:type_name -> slot_entry.MessageAddressTableLookup
	3, // 5: slot_entry.VersionedTransaction.message_legacy:type_name -> slot_entry.VersionedMessageLegacy
	4, // 6: slot_entry.VersionedTransaction.message_v0:type_name -> slot_entry.VersionedMessageV0
	5, // 7: slot_entry.Entry.transactions:type_name -> slot_entry.VersionedTransaction
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_slot_entry_proto_init() }
func file_slot_entry_proto_init() {
	if File_slot_entry_proto != nil {
		return
	}
	file_slot_entry_proto_msgTypes[5].OneofWrappers = []any{
		(*VersionedTransaction_MessageLegacy)(nil),
		(*VersionedTransaction_MessageV0)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slot_entry_proto_rawDesc), len(file_slot_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slot_entry_proto_goTypes,
		DependencyIndexes: file_slot_entry_proto_depIdxs,
		MessageInfos:      file_slot_entry_proto_msgTypes,
	}.Build()
	File_slot_entry_proto = out.File
	file_slot_entry_proto_goTypes = nil
	file_slot_entry_proto_depIdxs = nil
}
