// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slot_entry.proto

package overcast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageHeader struct {
	NumRequiredSignatures       uint32   `protobuf:"varint,1,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32   `protobuf:"varint,2,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32   `protobuf:"varint,3,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_f71c89f54dfce813, []int{0}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetNumRequiredSignatures() uint32 {
	if m != nil {
		return m.NumRequiredSignatures
	}
	return 0
}

func (m *MessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if m != nil {
		return m.NumReadonlySignedAccounts
	}
	return 0
}

func (m *MessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if m != nil {
		return m.NumReadonlyUnsignedAccounts
	}
	return 0
}

type CompiledInstruction struct {
	ProgramIdIndex       uint32   `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Accounts             []byte   `protobuf:"bytes,2,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompiledInstruction) Reset()         { *m = CompiledInstruction{} }
func (m *CompiledInstruction) String() string { return proto.CompactTextString(m) }
func (*CompiledInstruction) ProtoMessage()    {}
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f71c89f54dfce813, []int{1}
}

func (m *CompiledInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompiledInstruction.Unmarshal(m, b)
}
func (m *CompiledInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompiledInstruction.Marshal(b, m, deterministic)
}
func (m *CompiledInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompiledInstruction.Merge(m, src)
}
func (m *CompiledInstruction) XXX_Size() int {
	return xxx_messageInfo_CompiledInstruction.Size(m)
}
func (m *CompiledInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_CompiledInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_CompiledInstruction proto.InternalMessageInfo

func (m *CompiledInstruction) GetProgramIdIndex() uint32 {
	if m != nil {
		return m.ProgramIdIndex
	}
	return 0
}

func (m *CompiledInstruction) GetAccounts() []byte {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *CompiledInstruction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MessageAddressTableLookup struct {
	// 32 bytes pubkey
	AccountKey           []byte   `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WritableIndexes      []byte   `protobuf:"bytes,2,opt,name=writable_indexes,json=writableIndexes,proto3" json:"writable_indexes,omitempty"`
	ReadonlyIndexes      []byte   `protobuf:"bytes,3,opt,name=readonly_indexes,json=readonlyIndexes,proto3" json:"readonly_indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageAddressTableLookup) Reset()         { *m = MessageAddressTableLookup{} }
func (m *MessageAddressTableLookup) String() string { return proto.CompactTextString(m) }
func (*MessageAddressTableLookup) ProtoMessage()    {}
func (*MessageAddressTableLookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_f71c89f54dfce813, []int{2}
}

func (m *MessageAddressTableLookup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageAddressTableLookup.Unmarshal(m, b)
}
func (m *MessageAddressTableLookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageAddressTableLookup.Marshal(b, m, deterministic)
}
func (m *MessageAddressTableLookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageAddressTableLookup.Merge(m, src)
}
func (m *MessageAddressTableLookup) XXX_Size() int {
	return xxx_messageInfo_MessageAddressTableLookup.Size(m)
}
func (m *MessageAddressTableLookup) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageAddressTableLookup.DiscardUnknown(m)
}

var xxx_messageInfo_MessageAddressTableLookup proto.InternalMessageInfo

func (m *MessageAddressTableLookup) GetAccountKey() []byte {
	if m != nil {
		return m.AccountKey
	}
	return nil
}

func (m *MessageAddressTableLookup) GetWritableIndexes() []byte {
	if m != nil {
		return m.WritableIndexes
	}
	return nil
}

func (m *MessageAddressTableLookup) GetReadonlyIndexes() []byte {
	if m != nil {
		return m.ReadonlyIndexes
	}
	return nil
}

type VersionedMessageLegacy struct {
	Header *MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Each key is a 32 bytes pubkey
	AccountKeys [][]byte `protobuf:"bytes,2,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	// 32 byte hash
	RecentBlockhash      []byte                 `protobuf:"bytes,3,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Instructions         []*CompiledInstruction `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VersionedMessageLegacy) Reset()         { *m = VersionedMessageLegacy{} }
func (m *VersionedMessageLegacy) String() string { return proto.CompactTextString(m) }
func (*VersionedMessageLegacy) ProtoMessage()    {}
func (*VersionedMessageLegacy) Descriptor() ([]byte, []int) {
	return fileDescriptor_f71c89f54dfce813, []int{3}
}

func (m *VersionedMessageLegacy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedMessageLegacy.Unmarshal(m, b)
}
func (m *VersionedMessageLegacy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedMessageLegacy.Marshal(b, m, deterministic)
}
func (m *VersionedMessageLegacy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedMessageLegacy.Merge(m, src)
}
func (m *VersionedMessageLegacy) XXX_Size() int {
	return xxx_messageInfo_VersionedMessageLegacy.Size(m)
}
func (m *VersionedMessageLegacy) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedMessageLegacy.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedMessageLegacy proto.InternalMessageInfo

func (m *VersionedMessageLegacy) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *VersionedMessageLegacy) GetAccountKeys() [][]byte {
	if m != nil {
		return m.AccountKeys
	}
	return nil
}

func (m *VersionedMessageLegacy) GetRecentBlockhash() []byte {
	if m != nil {
		return m.RecentBlockhash
	}
	return nil
}

func (m *VersionedMessageLegacy) GetInstructions() []*CompiledInstruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type VersionedMessageV0 struct {
	Header *MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Each key is a 32 bytes pubkey
	AccountKeys [][]byte `protobuf:"bytes,2,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	// 32 byte hash
	RecentBlockhash      []byte                       `protobuf:"bytes,3,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Instructions         []*CompiledInstruction       `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty"`
	AddressTableLookups  []*MessageAddressTableLookup `protobuf:"bytes,5,rep,name=address_table_lookups,json=addressTableLookups,proto3" json:"address_table_lookups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *VersionedMessageV0) Reset()         { *m = VersionedMessageV0{} }
func (m *VersionedMessageV0) String() string { return proto.CompactTextString(m) }
func (*VersionedMessageV0) ProtoMessage()    {}
func (*VersionedMessageV0) Descriptor() ([]byte, []int) {
	return fileDescriptor_f71c89f54dfce813, []int{4}
}

func (m *VersionedMessageV0) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedMessageV0.Unmarshal(m, b)
}
func (m *VersionedMessageV0) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedMessageV0.Marshal(b, m, deterministic)
}
func (m *VersionedMessageV0) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedMessageV0.Merge(m, src)
}
func (m *VersionedMessageV0) XXX_Size() int {
	return xxx_messageInfo_VersionedMessageV0.Size(m)
}
func (m *VersionedMessageV0) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedMessageV0.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedMessageV0 proto.InternalMessageInfo

func (m *VersionedMessageV0) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *VersionedMessageV0) GetAccountKeys() [][]byte {
	if m != nil {
		return m.AccountKeys
	}
	return nil
}

func (m *VersionedMessageV0) GetRecentBlockhash() []byte {
	if m != nil {
		return m.RecentBlockhash
	}
	return nil
}

func (m *VersionedMessageV0) GetInstructions() []*CompiledInstruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

func (m *VersionedMessageV0) GetAddressTableLookups() []*MessageAddressTableLookup {
	if m != nil {
		return m.AddressTableLookups
	}
	return nil
}

type VersionedTransaction struct {
	// Each signature is 64 bytes
	Signatures [][]byte `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*VersionedTransaction_MessageLegacy
	//	*VersionedTransaction_MessageV0
	Message              isVersionedTransaction_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *VersionedTransaction) Reset()         { *m = VersionedTransaction{} }
func (m *VersionedTransaction) String() string { return proto.CompactTextString(m) }
func (*VersionedTransaction) ProtoMessage()    {}
func (*VersionedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f71c89f54dfce813, []int{5}
}

func (m *VersionedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedTransaction.Unmarshal(m, b)
}
func (m *VersionedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedTransaction.Marshal(b, m, deterministic)
}
func (m *VersionedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedTransaction.Merge(m, src)
}
func (m *VersionedTransaction) XXX_Size() int {
	return xxx_messageInfo_VersionedTransaction.Size(m)
}
func (m *VersionedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedTransaction proto.InternalMessageInfo

func (m *VersionedTransaction) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type isVersionedTransaction_Message interface {
	isVersionedTransaction_Message()
}

type VersionedTransaction_MessageLegacy struct {
	MessageLegacy *VersionedMessageLegacy `protobuf:"bytes,2,opt,name=message_legacy,json=messageLegacy,proto3,oneof"`
}

type VersionedTransaction_MessageV0 struct {
	MessageV0 *VersionedMessageV0 `protobuf:"bytes,3,opt,name=message_v0,json=messageV0,proto3,oneof"`
}

func (*VersionedTransaction_MessageLegacy) isVersionedTransaction_Message() {}

func (*VersionedTransaction_MessageV0) isVersionedTransaction_Message() {}

func (m *VersionedTransaction) GetMessage() isVersionedTransaction_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *VersionedTransaction) GetMessageLegacy() *VersionedMessageLegacy {
	if x, ok := m.GetMessage().(*VersionedTransaction_MessageLegacy); ok {
		return x.MessageLegacy
	}
	return nil
}

func (m *VersionedTransaction) GetMessageV0() *VersionedMessageV0 {
	if x, ok := m.GetMessage().(*VersionedTransaction_MessageV0); ok {
		return x.MessageV0
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VersionedTransaction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VersionedTransaction_MessageLegacy)(nil),
		(*VersionedTransaction_MessageV0)(nil),
	}
}

type Entry struct {
	NumHashes uint64 `protobuf:"varint,1,opt,name=num_hashes,json=numHashes,proto3" json:"num_hashes,omitempty"`
	// fixed size, 32 bytes
	Hash                 []byte                  `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Transactions         []*VersionedTransaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f71c89f54dfce813, []int{6}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetNumHashes() uint64 {
	if m != nil {
		return m.NumHashes
	}
	return 0
}

func (m *Entry) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Entry) GetTransactions() []*VersionedTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageHeader)(nil), "slot_entry.MessageHeader")
	proto.RegisterType((*CompiledInstruction)(nil), "slot_entry.CompiledInstruction")
	proto.RegisterType((*MessageAddressTableLookup)(nil), "slot_entry.MessageAddressTableLookup")
	proto.RegisterType((*VersionedMessageLegacy)(nil), "slot_entry.VersionedMessageLegacy")
	proto.RegisterType((*VersionedMessageV0)(nil), "slot_entry.VersionedMessageV0")
	proto.RegisterType((*VersionedTransaction)(nil), "slot_entry.VersionedTransaction")
	proto.RegisterType((*Entry)(nil), "slot_entry.Entry")
}

func init() {
	proto.RegisterFile("slot_entry.proto", fileDescriptor_f71c89f54dfce813)
}

var fileDescriptor_f71c89f54dfce813 = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0xf6, 0x07, 0x3d, 0xc9, 0x7e, 0xe4, 0x31, 0xe8, 0xf8, 0xd9, 0x46, 0x24, 0xa4, 0x72,
	0x33, 0x46, 0x91, 0xb8, 0x9d, 0xd6, 0x82, 0xd4, 0x6a, 0xe3, 0xc6, 0x1b, 0x95, 0xe0, 0x26, 0x72,
	0x63, 0xab, 0x8d, 0x9a, 0xd8, 0xc5, 0x76, 0x06, 0xbd, 0xe3, 0x19, 0x78, 0x17, 0x1e, 0x03, 0xf1,
	0x06, 0x3c, 0x0b, 0xb2, 0xe3, 0xb4, 0xc9, 0x56, 0xf1, 0x00, 0xdc, 0xc5, 0x5f, 0xce, 0x77, 0xfc,
	0x9d, 0x73, 0xbe, 0x63, 0xd8, 0x55, 0xa9, 0xd0, 0x11, 0xe3, 0x5a, 0xce, 0x4e, 0xa6, 0x52, 0x68,
	0x81, 0x60, 0x81, 0x84, 0xbf, 0x3c, 0xd8, 0xfa, 0xc0, 0x94, 0x22, 0x23, 0xd6, 0x63, 0x84, 0x32,
	0x89, 0xde, 0xc2, 0x23, 0x9e, 0x67, 0x91, 0x64, 0x5f, 0xf2, 0x44, 0x32, 0x1a, 0xa9, 0x64, 0xc4,
	0x89, 0xce, 0x25, 0x53, 0x4d, 0xef, 0xd8, 0x6b, 0x6d, 0xe1, 0x7d, 0x9e, 0x67, 0xd8, 0xfd, 0xbd,
	0x9a, 0xff, 0x44, 0x67, 0xf0, 0xb4, 0xe0, 0x11, 0x2a, 0x78, 0x3a, 0xb3, 0x3c, 0x46, 0x23, 0x12,
	0xc7, 0x22, 0xe7, 0x5a, 0x35, 0x57, 0x2d, 0xf9, 0xc0, 0x92, 0x8b, 0x90, 0x2b, 0x1b, 0x71, 0xee,
	0x02, 0x50, 0x17, 0x0e, 0x6b, 0x09, 0x72, 0x7e, 0x3b, 0xc5, 0x9a, 0x4d, 0xf1, 0xa4, 0x92, 0xe2,
	0xa3, 0x8b, 0x29, 0x93, 0x84, 0x02, 0xf6, 0xba, 0x22, 0x9b, 0x26, 0x29, 0xa3, 0x7d, 0xae, 0xb4,
	0xcc, 0x63, 0x9d, 0x08, 0x8e, 0x5a, 0xb0, 0x3b, 0x95, 0x62, 0x24, 0x49, 0x16, 0x25, 0x34, 0x4a,
	0x38, 0x65, 0xdf, 0x5c, 0x35, 0xdb, 0x0e, 0xef, 0xd3, 0xbe, 0x41, 0xd1, 0x63, 0xb8, 0x5f, 0x93,
	0x1c, 0xe0, 0xf9, 0x19, 0x21, 0x58, 0xa7, 0x44, 0x13, 0xab, 0x23, 0xc0, 0xf6, 0x3b, 0xfc, 0xe1,
	0xc1, 0x81, 0x6b, 0xe0, 0x39, 0xa5, 0x92, 0x29, 0x75, 0x4d, 0x86, 0x29, 0xbb, 0x14, 0x62, 0x92,
	0x4f, 0xd1, 0x11, 0xf8, 0x8e, 0x1d, 0x4d, 0xd8, 0xcc, 0x5e, 0x19, 0x60, 0x70, 0xd0, 0x05, 0x9b,
	0xa1, 0x97, 0xb0, 0xfb, 0x55, 0x26, 0xda, 0x50, 0x0a, 0x59, 0xac, 0xbc, 0x76, 0xa7, 0xc4, 0xfb,
	0x05, 0x6c, 0x42, 0xe7, 0xbd, 0x29, 0x43, 0x0b, 0x25, 0x3b, 0x25, 0xee, 0x42, 0xc3, 0x3f, 0x1e,
	0x3c, 0x1c, 0x30, 0xa9, 0x12, 0xc1, 0x19, 0x75, 0xea, 0x2e, 0xd9, 0x88, 0xc4, 0x33, 0xf4, 0x1a,
	0x36, 0xc7, 0x76, 0xd0, 0x56, 0x8c, 0xdf, 0x3e, 0x38, 0xa9, 0xf8, 0xa3, 0xe6, 0x04, 0xec, 0x02,
	0xd1, 0x73, 0x08, 0x2a, 0x45, 0x18, 0x7d, 0x6b, 0xad, 0x00, 0xfb, 0x8b, 0x2a, 0x9c, 0xb6, 0x98,
	0x71, 0x1d, 0x0d, 0x53, 0x11, 0x4f, 0xc6, 0x44, 0x8d, 0x17, 0xda, 0x0c, 0xde, 0x29, 0x61, 0xd4,
	0x85, 0x20, 0x59, 0x4c, 0x46, 0x35, 0xd7, 0x8f, 0xd7, 0x5a, 0x7e, 0xfb, 0xa8, 0x2a, 0x63, 0xc9,
	0x04, 0x71, 0x8d, 0x14, 0xfe, 0x5c, 0x05, 0x74, 0xbb, 0xc0, 0xc1, 0xe9, 0xff, 0x51, 0x1c, 0xfa,
	0x04, 0xfb, 0xa4, 0xb0, 0x52, 0x54, 0x18, 0x23, 0xb5, 0x66, 0x52, 0xcd, 0x0d, 0x9b, 0xed, 0xc5,
	0x92, 0xa2, 0xee, 0x5a, 0x0f, 0xef, 0x91, 0x3b, 0x98, 0x0a, 0x7f, 0x7b, 0xf0, 0x60, 0xde, 0xb7,
	0x6b, 0x49, 0xb8, 0x22, 0xc5, 0x82, 0x1c, 0x02, 0xd4, 0x16, 0xdd, 0x34, 0xa1, 0x82, 0xa0, 0x0b,
	0xd8, 0xce, 0x8a, 0xab, 0xa2, 0xd4, 0x1a, 0xc9, 0xba, 0xd4, 0x6f, 0x87, 0x55, 0x31, 0xcb, 0x2d,
	0xd7, 0x5b, 0xc1, 0x5b, 0x59, 0xcd, 0x83, 0x67, 0x00, 0x65, 0xb2, 0x9b, 0x53, 0xdb, 0x4a, 0xbf,
	0x7d, 0xf8, 0xaf, 0x44, 0x83, 0xd3, 0xde, 0x0a, 0x6e, 0x64, 0xe5, 0xa1, 0xd3, 0x80, 0x7b, 0xee,
	0x10, 0x7e, 0xf7, 0x60, 0xe3, 0xbd, 0x21, 0xa1, 0x67, 0x00, 0xe6, 0xfd, 0x30, 0x73, 0x70, 0x6f,
	0xd5, 0x3a, 0x6e, 0xf0, 0x3c, 0xeb, 0x59, 0xc0, 0x2c, 0xaf, 0x9d, 0x5c, 0xb1, 0x5d, 0xf6, 0x1b,
	0xbd, 0x83, 0x40, 0x2f, 0x9a, 0x60, 0xd6, 0xc9, 0x34, 0xf8, 0x78, 0xa9, 0x94, 0x4a, 0xb7, 0x70,
	0x8d, 0xd5, 0xf1, 0x3f, 0x37, 0x5e, 0x89, 0x1b, 0x26, 0x63, 0xa2, 0xf4, 0x70, 0xd3, 0xbe, 0xb1,
	0x6f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xff, 0x6b, 0x2e, 0x01, 0x77, 0x05, 0x00, 0x00,
}
