// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: slot_stream.proto

package overcast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SlotStream_StreamSlots_FullMethodName = "/slot_stream.SlotStream/StreamSlots"
)

// SlotStreamClient is the client API for SlotStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlotStreamClient interface {
	StreamSlots(ctx context.Context, in *SlotStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SlotResponse], error)
}

type slotStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewSlotStreamClient(cc grpc.ClientConnInterface) SlotStreamClient {
	return &slotStreamClient{cc}
}

func (c *slotStreamClient) StreamSlots(ctx context.Context, in *SlotStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SlotResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SlotStream_ServiceDesc.Streams[0], SlotStream_StreamSlots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SlotStreamRequest, SlotResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SlotStream_StreamSlotsClient = grpc.ServerStreamingClient[SlotResponse]

// SlotStreamServer is the server API for SlotStream service.
// All implementations must embed UnimplementedSlotStreamServer
// for forward compatibility.
type SlotStreamServer interface {
	StreamSlots(*SlotStreamRequest, grpc.ServerStreamingServer[SlotResponse]) error
	mustEmbedUnimplementedSlotStreamServer()
}

// UnimplementedSlotStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSlotStreamServer struct{}

func (UnimplementedSlotStreamServer) StreamSlots(*SlotStreamRequest, grpc.ServerStreamingServer[SlotResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSlots not implemented")
}
func (UnimplementedSlotStreamServer) mustEmbedUnimplementedSlotStreamServer() {}
func (UnimplementedSlotStreamServer) testEmbeddedByValue()                    {}

// UnsafeSlotStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlotStreamServer will
// result in compilation errors.
type UnsafeSlotStreamServer interface {
	mustEmbedUnimplementedSlotStreamServer()
}

func RegisterSlotStreamServer(s grpc.ServiceRegistrar, srv SlotStreamServer) {
	// If the following call pancis, it indicates UnimplementedSlotStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SlotStream_ServiceDesc, srv)
}

func _SlotStream_StreamSlots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SlotStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SlotStreamServer).StreamSlots(m, &grpc.GenericServerStream[SlotStreamRequest, SlotResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SlotStream_StreamSlotsServer = grpc.ServerStreamingServer[SlotResponse]

// SlotStream_ServiceDesc is the grpc.ServiceDesc for SlotStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlotStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slot_stream.SlotStream",
	HandlerType: (*SlotStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSlots",
			Handler:       _SlotStream_StreamSlots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "slot_stream.proto",
}
